
-- =====================================================
-- Triggers para Auto-increment
-- =====================================================

-- Trigger para CAT_ESTATUS
CREATE TRIGGER TR_CAT_ESTATUS_BI FOR CAT_ESTATUS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ESTATUS_KEY IS NULL OR NEW.ESTATUS_KEY <= 0) THEN
        NEW.ESTATUS_KEY = GEN_ID(GEN_CAT_ESTATUS, 1);
END;

-- Trigger para CAT_USUARIOS
CREATE TRIGGER TR_CAT_USUARIOS_BI FOR CAT_USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.USUARIOS_KEY IS NULL) THEN
        NEW.USUARIOS_KEY = GEN_ID(GEN_CAT_USUARIOS, 1);
END;

-- Trigger para CAT_PROYECTOS
CREATE TRIGGER TR_CAT_PROYECTOS_BI FOR CAT_PROYECTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.PROYECTO_KEY IS NULL) THEN
        NEW.PROYECTO_KEY = GEN_ID(GEN_CAT_PROYECTOS, 1);
END;

-- Trigger para CAT_PERMISOS
CREATE TRIGGER TR_CAT_PERMISOS_BI FOR CAT_PERMISOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.PERMISO_KEY IS NULL) THEN
        NEW.PERMISO_KEY = GEN_ID(GEN_CAT_PERMISOS, 1);
END;

-- Trigger para CAT_PERFILES
CREATE TRIGGER TR_CAT_PERFILES_BI FOR CAT_PERFILES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.PERFIL_KEY IS NULL) THEN
        NEW.PERFIL_KEY = GEN_ID(GEN_CAT_PERFILES, 1);
END;

-- Trigger para CAT_BASES
CREATE TRIGGER TR_CAT_BASES_BI FOR CAT_BASES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.BASE_KEY IS NULL) THEN
        NEW.BASE_KEY = GEN_ID(GEN_CAT_BASES, 1);
END;

-- Trigger para CAT_POSTES
CREATE TRIGGER TR_CAT_POSTES_BI FOR CAT_POSTES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.POSTE_KEY IS NULL) THEN
        NEW.POSTE_KEY = GEN_ID(GEN_CAT_POSTES, 1);
END;

-- Trigger para CAT_BRAZOS
CREATE TRIGGER TR_CAT_BRAZOS_BI FOR CAT_BRAZOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.BRAZO_KEY IS NULL) THEN
        NEW.BRAZO_KEY = GEN_ID(GEN_CAT_BRAZOS, 1);
END;

-- Trigger para CAT_LUMINARIAS
CREATE TRIGGER TR_CAT_LUMINARIAS_BI FOR CAT_LUMINARIAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ILUMINARIAS_KEY IS NULL) THEN
        NEW.ILUMINARIAS_KEY = GEN_ID(GEN_CAT_LUMINARIAS, 1);
END;

-- Trigger para CAT_LAMPARAS
CREATE TRIGGER TR_CAT_LAMPARAS_BI FOR CAT_LAMPARAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.LAMPARA_KEY IS NULL) THEN
        NEW.LAMPARA_KEY = GEN_ID(GEN_CAT_LAMPARAS, 1);
END;

-- Trigger para CAT_ALMACENES
CREATE TRIGGER TR_CAT_ALMACENES_BI FOR CAT_ALMACENES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ALMACEN_KEY IS NULL) THEN
        NEW.ALMACEN_KEY = GEN_ID(GEN_CAT_ALMACENES, 1);
END;

-- Trigger para CAT_CUADRILLAS
CREATE TRIGGER TR_CAT_CUADRILLAS_BI FOR CAT_CUADRILLAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.CUADRILLA_KEY IS NULL) THEN
        NEW.CUADRILLA_KEY = GEN_ID(GEN_CAT_CUADRILLAS, 1);
END;

-- Trigger para CAT_ESTADOS
CREATE TRIGGER TR_CAT_ESTADOS_BI FOR CAT_ESTADOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ESTADO_KEY IS NULL) THEN
        NEW.ESTADO_KEY = GEN_ID(GEN_CAT_ESTADOS, 1);
END;

-- Trigger para CAT_MUNICIPIOS
CREATE TRIGGER TR_CAT_MUNICIPIOS_BI FOR CAT_MUNICIPIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.MUNICIPIO_KEY IS NULL) THEN
        NEW.MUNICIPIO_KEY = GEN_ID(GEN_CAT_MUNICIPIOS, 1);
END;

-- Trigger para CAT_LOCALIDADES
CREATE TRIGGER TR_CAT_LOCALIDADES_BI FOR CAT_LOCALIDADES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.LOCALIDAD_KEY IS NULL) THEN
        NEW.LOCALIDAD_KEY = GEN_ID(GEN_CAT_LOCALIDADES, 1);
END;

-- Trigger para ALMACEN_PROYECTO
CREATE TRIGGER TR_ALMACEN_PROYECTO_BI FOR ALMACEN_PROYECTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ALMACEN_PROYECTO_KEY IS NULL) THEN
        NEW.ALMACEN_PROYECTO_KEY = GEN_ID(GEN_ALMACEN_PROYECTO, 1);
END;

-- Trigger para CUADRILLA_PROYECTO
CREATE TRIGGER TR_CUADRILLA_PROYECTO_BI FOR CUADRILLA_PROYECTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.CUADRILLA_PROYECTO_KEY IS NULL) THEN
        NEW.CUADRILLA_PROYECTO_KEY = GEN_ID(GEN_CUADRILLA_PROYECTO, 1);
END;

-- Trigger para USUARIO_PROYECTO
CREATE TRIGGER TR_USUARIO_PROYECTO_BI FOR USUARIO_PROYECTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.USUARIO_PROYECTO_KEY IS NULL) THEN
        NEW.USUARIO_PROYECTO_KEY = GEN_ID(GEN_USUARIO_PROYECTO, 1);
END;

-- Trigger para USUARIO_PERFIL
CREATE TRIGGER TR_USUARIO_PERFIL_BI FOR USUARIO_PERFIL
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.USUARIO_PERFIL_KEY IS NULL) THEN
        NEW.USUARIO_PERFIL_KEY = GEN_ID(GEN_USUARIO_PERFIL, 1);
END;

-- Trigger para PERFIL_PERMISO
CREATE TRIGGER TR_PERFIL_PERMISO_BI FOR PERFIL_PERMISO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.PERFIL_PERMISO_KEY IS NULL) THEN
        NEW.PERFIL_PERMISO_KEY = GEN_ID(GEN_PERFIL_PERMISO, 1);
END;

-- =====================================================
-- Triggers para Actualización de Fecha_Modificacion
-- =====================================================

-- Trigger para actualizar fecha_modificacion en CAT_ESTATUS
CREATE TRIGGER TR_CAT_ESTATUS_BU FOR CAT_ESTATUS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_USUARIOS
CREATE TRIGGER TR_CAT_USUARIOS_BU FOR CAT_USUARIOS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_PROYECTOS
CREATE TRIGGER TR_CAT_PROYECTOS_BU FOR CAT_PROYECTOS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_PERMISOS
CREATE TRIGGER TR_CAT_PERMISOS_BU FOR CAT_PERMISOS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_PERFILES
CREATE TRIGGER TR_CAT_PERFILES_BU FOR CAT_PERFILES
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_BASES
CREATE TRIGGER TR_CAT_BASES_BU FOR CAT_BASES
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_POSTES
CREATE TRIGGER TR_CAT_POSTES_BU FOR CAT_POSTES
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_BRAZOS
CREATE TRIGGER TR_CAT_BRAZOS_BU FOR CAT_BRAZOS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_LUMINARIAS
CREATE TRIGGER TR_CAT_LUMINARIAS_BU FOR CAT_LUMINARIAS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_LAMPARAS
CREATE TRIGGER TR_CAT_LAMPARAS_BU FOR CAT_LAMPARAS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_ALMACENES
CREATE TRIGGER TR_CAT_ALMACENES_BU FOR CAT_ALMACENES
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_CUADRILLAS
CREATE TRIGGER TR_CAT_CUADRILLAS_BU FOR CAT_CUADRILLAS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_ESTADOS
CREATE TRIGGER TR_CAT_ESTADOS_BU FOR CAT_ESTADOS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_MUNICIPIOS
CREATE TRIGGER TR_CAT_MUNICIPIOS_BU FOR CAT_MUNICIPIOS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;

-- Trigger para actualizar fecha_modificacion en CAT_LOCALIDADES
CREATE TRIGGER TR_CAT_LOCALIDADES_BU FOR CAT_LOCALIDADES
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP;
END;