SET TERM ^ ;

CREATE OR ALTER PROCEDURE CTLIGHT_SET_CAT_LAMPARAS (
    P_LAMPARA_KEY INTEGER,
    P_CODIGO_LAMPARA VARCHAR(50),
    P_DESCRIPCION_LAMPARA VARCHAR(100),
    P_POTENCIA DECIMAL(6,2),
    P_VIDA_UTIL_HORAS INTEGER,
    P_ESTATUS_LINK INTEGER
)
RETURNS (
    LAMPARA_KEY INTEGER,
    RESULTADO INTEGER,
    MSG VARCHAR(100)
)
AS
DECLARE VARIABLE V_LAMPARA_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
    V_CODE = 0;
    V_MSG = '';
    V_LAMPARA_KEY = 0;

    IF (:P_LAMPARA_KEY = 0) THEN
    BEGIN
		INSERT INTO CAT_LAMPARAS (CODIGO_LAMPARA, DESCRIPCION_LAMPARA, POTENCIA, VIDA_UTIL_HORAS, ESTATUS_LINK)
		VALUES (:P_CODIGO_LAMPARA, :P_DESCRIPCION_LAMPARA, :P_POTENCIA, :P_VIDA_UTIL_HORAS, :P_ESTATUS_LINK)
		RETURNING LAMPARA_KEY INTO :V_LAMPARA_KEY;
    END
    ELSE IF (:P_LAMPARA_KEY > 0) THEN
    BEGIN
		IF (NOT EXISTS(SELECT LAMPARA_KEY
				FROM CAT_LAMPARAS
				WHERE (LAMPARA_KEY = :P_LAMPARA_KEY))) THEN
		BEGIN
			V_MSG = 'No existe un registro con este key';
		END
        UPDATE CAT_LAMPARAS
        SET DESCRIPCION_LAMPARA = :P_DESCRIPCION_LAMPARA,
            CODIGO_LAMPARA = :P_CODIGO_LAMPARA,
            POTENCIA = :P_POTENCIA,
            VIDA_UTIL_HORAS = :P_VIDA_UTIL_HORAS,
            ESTATUS_LINK = :P_ESTATUS_LINK,
            FECHA_MODIFICACION = CURRENT_TIMESTAMP
        WHERE LAMPARA_KEY = :P_LAMPARA_KEY;
    END

    IF (ROW_COUNT > 0) THEN
    BEGIN
        V_CODE = 1;
        V_MSG = 'Información guardada correctamente';
    END
    ELSE
    BEGIN
        V_CODE = 0;
        V_MSG = 'No se pudo guardar la información';
    END

    RESULTADO = V_CODE;
    LAMPARA_KEY = V_LAMPARA_KEY;
    MSG = V_MSG;
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_DEL_CAT_LAMPARAS (
    P_LAMPARA_KEY INTEGER
)
RETURNS (
    LAMPARA_KEY INTEGER,
    RESULTADO INTEGER,
    MSG VARCHAR(100)
)
AS
DECLARE VARIABLE V_LAMPARA_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
    V_CODE = 0;
    V_MSG = '';
    V_LAMPARA_KEY = 0;

    IF (NOT EXISTS(SELECT LAMPARA_KEY
		FROM CAT_LAMPARAS
		WHERE (LAMPARA_KEY = :P_LAMPARA_KEY))) THEN
	BEGIN
		V_MSG = 'No existe un registro con este key';
	END

    UPDATE CAT_LAMPARAS
    SET ESTATUS_LINK = 2,
        FECHA_MODIFICACION = CURRENT_TIMESTAMP
    WHERE LAMPARA_KEY = :P_LAMPARA_KEY;
    IF (ROW_COUNT > 0) THEN
    BEGIN
        V_CODE = 1;
        V_MSG = 'Registro eliminado correctamente';
    END
    ELSE
    BEGIN
        V_CODE = 0;
        V_MSG = 'No se pudo eliminar el registro';
    END
    RESULTADO = V_CODE;
    LAMPARA_KEY = V_LAMPARA_KEY;
    MSG = V_MSG;
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_GET_CAT_LAMPARAS (
    P_LAMPARA_KEY INTEGER = 0,
    P_ONLY_ACTIVE SMALLINT = 0
)
RETURNS (
    LAMPARA_KEY INTEGER,
    CODIGO_LAMPARA VARCHAR(50),
    DESCRIPCION_LAMPARA VARCHAR(100),
    POTENCIA DECIMAL(6,2),
    VIDA_UTIL_HORAS INTEGER,
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ESTATUS_LINK INTEGER
)
AS
BEGIN
    IF (:P_LAMPARA_KEY = 0) THEN
    BEGIN
        -- Retornar listado completo
        FOR
            SELECT LAMPARA_KEY, CODIGO_LAMPARA, DESCRIPCION_LAMPARA, POTENCIA, VIDA_UTIL_HORAS, FECHA_CREACION, FECHA_MODIFICACION, ESTATUS_LINK
            FROM CAT_LAMPARAS
            WHERE (:P_ONLY_ACTIVE = 0 OR ESTATUS_LINK = 1)
            INTO :LAMPARA_KEY, :CODIGO_LAMPARA, :DESCRIPCION_LAMPARA, :POTENCIA, :VIDA_UTIL_HORAS, :FECHA_CREACION, :FECHA_MODIFICACION, :ESTATUS_LINK
        DO
            SUSPEND;
    END
    ELSE IF (:P_LAMPARA_KEY > 0) THEN
    BEGIN
        -- Retornar solo un registro específico
        FOR
            SELECT LAMPARA_KEY, CODIGO_LAMPARA, DESCRIPCION_LAMPARA, POTENCIA, VIDA_UTIL_HORAS, FECHA_CREACION, FECHA_MODIFICACION, ESTATUS_LINK
            FROM CAT_LAMPARAS
            WHERE LAMPARA_KEY = :P_LAMPARA_KEY
            INTO :LAMPARA_KEY, :CODIGO_LAMPARA, :DESCRIPCION_LAMPARA, :POTENCIA, :VIDA_UTIL_HORAS, :FECHA_CREACION, :FECHA_MODIFICACION, :ESTATUS_LINK
        DO
            SUSPEND;
    END
END^

SET TERM ; ^