SET TERM ^ ;

CREATE OR ALTER PROCEDURE CTLIGHT_SET_CAT_ESTADOS (
    P_ESTADO_KEY INTEGER,
    P_CLAVE_ESTADO VARCHAR(20),
    P_NOMBRE VARCHAR(100),
    P_NOMBRE_ABREVIADO VARCHAR(100)
)
RETURNS (
    ESTADO_KEY INTEGER,
    RESULTADO INTEGER,
    MSG VARCHAR(100)
)
AS
DECLARE VARIABLE V_ESTADO_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
    V_CODE = 0;
    V_MSG = '';
    V_ESTADO_KEY = 0;

    IF (:P_ESTADO_KEY = 0) THEN
    BEGIN
		INSERT INTO CAT_ESTADOS (CLAVE_ESTADO, NOMBRE, NOMBRE_ABREVIADO)
		VALUES (:P_CLAVE_ESTADO, :P_NOMBRE, :P_NOMBRE_ABREVIADO)
		RETURNING ESTADO_KEY INTO :V_ESTADO_KEY;
    END
    ELSE IF (:P_ESTADO_KEY > 0) THEN
    BEGIN
		IF (NOT EXISTS(SELECT ESTADO_KEY
				FROM CAT_ESTADOS
				WHERE (ESTADO_KEY = :P_ESTADO_KEY))) THEN
		BEGIN
			V_MSG = 'No existe un registro con este key';
		END
        UPDATE CAT_ESTADOS
        SET NOMBRE = :P_NOMBRE,
            NOMBRE_ABREVIADO = :P_NOMBRE_ABREVIADO,
            CLAVE_ESTADO = :P_CLAVE_ESTADO
            WHERE ESTADO_KEY = :P_ESTADO_KEY;
    END
    IF (ROW_COUNT > 0) THEN
    BEGIN
        V_CODE = 1;
        V_MSG = 'Información guardada correctamente';
    END
    ELSE
    BEGIN
        V_CODE = 0;
        V_MSG = 'No se pudo guardar la información';
    END

    RESULTADO = V_CODE;
    ESTADO_KEY = V_ESTADO_KEY;
    MSG = V_MSG;
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_GET_CAT_ESTADOS (
    P_ESTADO_KEY INTEGER = 0
)
RETURNS (
    ESTADO_KEY INTEGER,
    CLAVE_ESTADO VARCHAR(20),
    NOMBRE VARCHAR(100),
    NOMBRE_ABREVIADO VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
)
AS
BEGIN
    IF (:P_ESTADO_KEY = 0) THEN
    BEGIN
        -- Retornar listado completo
        FOR
            SELECT ESTADO_KEY, CLAVE_ESTADO, NOMBRE, NOMBRE_ABREVIADO, FECHA_CREACION, FECHA_MODIFICACION
            FROM CAT_ESTADOS
            INTO :ESTADO_KEY, :CLAVE_ESTADO, :NOMBRE, :NOMBRE_ABREVIADO, :FECHA_CREACION, :FECHA_MODIFICACION
        DO
            SUSPEND;
    END
    ELSE IF (:P_ESTADO_KEY > 0) THEN
    BEGIN
        -- Retornar solo un registro específico
        FOR
            SELECT ESTADO_KEY, CLAVE_ESTADO, NOMBRE, NOMBRE_ABREVIADO, FECHA_CREACION, FECHA_MODIFICACION
            FROM CAT_ESTADOS
            WHERE ESTADO_KEY = :P_ESTADO_KEY
            INTO :ESTADO_KEY, :CLAVE_ESTADO, :NOMBRE, :NOMBRE_ABREVIADO, :FECHA_CREACION, :FECHA_MODIFICACION
        DO
            SUSPEND;
    END
END^

SET TERM ; ^