CREATE GENERATOR GEN_CAT_CUADRILLAS;

CREATE TABLE CAT_CUADRILLAS (
    CUADRILLA_KEY INTEGER NOT NULL PRIMARY KEY,
    CLAVE_CUADRILLA VARCHAR(20),
    NOMBRE VARCHAR(100) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_CAT_CUADRILLAS_CUADRILLA_KEY ON CAT_CUADRILLAS (CUADRILLA_KEY);
CREATE UNIQUE INDEX IDX_CAT_CUADRILLAS_CLAVE_CUADRILLA ON CAT_CUADRILLAS (CLAVE_CUADRILLA);

ALTER TABLE CAT_CUADRILLAS ADD CONSTRAINT FK_CAT_CUADRILLAS_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CAT_CUADRILLAS_BI FOR CAT_CUADRILLAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.CUADRILLA_KEY IS NULL OR NEW.CUADRILLA_KEY <= 0) THEN
        NEW.CUADRILLA_KEY = GEN_ID(GEN_CAT_CUADRILLAS, 1);
END;