CREATE GENERATOR GEN_CAT_BASES;

CREATE TABLE CAT_BASES (
    BASE_KEY INTEGER NOT NULL PRIMARY KEY,
    CODIGO_BASE VARCHAR(50) NOT NULL,
    DESCRIPCION_BASE VARCHAR(100) NOT NULL,
    MATERIAL VARCHAR(50),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_CAT_BASES_BASE_KEY ON CAT_BASES (BASE_KEY);
CREATE UNIQUE INDEX IDX_CAT_BASES_CODIGO_BASE ON CAT_BASES (CODIGO_BASE);

ALTER TABLE CAT_BASES ADD CONSTRAINT FK_CAT_BASES_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CAT_BASES_BI FOR CAT_BASES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.BASE_KEY IS NULL OR NEW.BASE_KEY <= 0) THEN
        NEW.BASE_KEY = GEN_ID(GEN_CAT_BASES, 1);
END;