CREATE GENERATOR GEN_CAT_ESTATUS;

CREATE TABLE CAT_ESTATUS (
    ESTATUS_KEY INTEGER NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR(100) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IDX_CAT_ESTATUS_ESTATUS_KEY ON CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CAT_ESTATUS_BI FOR CAT_ESTATUS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ESTATUS_KEY IS NULL OR NEW.ESTATUS_KEY <= 0) THEN
        NEW.ESTATUS_KEY = GEN_ID(GEN_CAT_ESTATUS, 1);
END;

INSERT INTO CAT_ESTATUS (ESTATUS_KEY, DESCRIPCION) VALUES (1, 'ACTIVO');
INSERT INTO CAT_ESTATUS (ESTATUS_KEY, DESCRIPCION) VALUES (2, 'INACTIVO');