-- CAT_SERVICIOS_SMTP definition

-- Drop table

-- DROP TABLE CAT_SERVICIOS_SMTP;

CREATE TABLE CAT_SERVICIOS_SMTP (
	SERVICIOS_SMTP_KEY INTEGER NOT NULL,
	SMTP_HOST VARCHAR(30) NOT NULL,
	PUERTO VARCHAR(30) NOT NULL,
	PWD VARCHAR(30) NOT NULL,
	CORREO_REMITENTE VARCHAR(30) NOT NULL,
	PROYECTO_LINK INTEGER NOT NULL,
	ESTATUS_LINK INTEGER NOT NULL,
	CLAVE_PROYECTO_LINK VARCHAR(20),
	CONSTRAINT PK_CAT_SERVICIOS_SMTP PRIMARY KEY (SERVICIOS_SMTP_KEY),
	CONSTRAINT FK_CAT_SERVICIOS_SMTP_1 FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY)
);
CREATE INDEX FK_CAT_SERVICIOS_SMTP_1 ON CAT_SERVICIOS_SMTP (ESTATUS_LINK);

CREATE TRIGGER CAT_SERVICIOS_SMTP_BI FOR CAT_SERVICIOS_SMTP BEFORE INSERT
as
begin
  if (new.servicios_smtp_key is null or new.servicios_smtp_key <= 0 ) then
    new.servicios_smtp_key = gen_id(gen_cat_servicios_smtp_id,1);
end;