CREATE GENERATOR GEN_CAT_ESTADOS;

CREATE TABLE CAT_ESTADOS (
    ESTADO_KEY INTEGER NOT NULL PRIMARY KEY,
    CLAVE_ESTADO VARCHAR(20),
    NOMBRE VARCHAR(100) NOT NULL,
    NOMBRE_ABREVIADO VARCHAR(100) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IDX_CAT_ESTADOS_ESTADO_KEY ON CAT_ESTADOS (ESTADO_KEY);
CREATE UNIQUE INDEX IDX_CAT_ESTADOS_CLAVE_ESTADO ON CAT_ESTADOS (CLAVE_ESTADO);

CREATE TRIGGER TR_CAT_ESTADOS_BI FOR CAT_ESTADOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ESTADO_KEY IS NULL OR NEW.ESTADO_KEY <= 0) THEN
        NEW.ESTADO_KEY = GEN_ID(GEN_CAT_ESTADOS, 1);
END;