CREATE GENERATOR GEN_CAT_ALMACENES;

CREATE TABLE CAT_ALMACENES (
    ALMACEN_KEY INTEGER NOT NULL PRIMARY KEY,
    CLAVE_ALMACEN VARCHAR(20),
    NOMBRE VARCHAR(100) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_CAT_ALMACENES_ALMACEN_KEY ON CAT_ALMACENES (ALMACEN_KEY);
CREATE UNIQUE INDEX IDX_CAT_ALMACENES_CLAVE_ALMACEN ON CAT_ALMACENES (CLAVE_ALMACEN);

ALTER TABLE CAT_ALMACENES ADD CONSTRAINT FK_CAT_ALMACENES_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CAT_ALMACENES_BI FOR CAT_ALMACENES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ALMACEN_KEY IS NULL OR NEW.ALMACEN_KEY <= 0) THEN
        NEW.ALMACEN_KEY = GEN_ID(GEN_CAT_ALMACENES, 1);
END;