CREATE GENERATOR GEN_CAT_MUNICIPIOS;

CREATE TABLE CAT_MUNICIPIOS (
    MUNICIPIO_KEY INTEGER NOT NULL PRIMARY KEY,
    ESTADO_LINK INTEGER NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    CLAVE_MUNICIPIO VARCHAR(100),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IDX_CAT_MUNICIPIOS_MUNICIPIO_KEY ON CAT_MUNICIPIOS (MUNICIPIO_KEY);
CREATE UNIQUE INDEX IDX_CAT_MUNICIPIOS_CLAVE_MUNICIPIO ON CAT_MUNICIPIOS (CLAVE_MUNICIPIO);

ALTER TABLE CAT_MUNICIPIOS ADD CONSTRAINT FK_CAT_MUNICIPIOS_ESTATUS 
    FOREIGN KEY (ESTADO_LINK) REFERENCES CAT_ESTADOS (ESTADO_KEY);

CREATE TRIGGER TR_CAT_MUNICIPIOS_BI FOR CAT_MUNICIPIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.MUNICIPIO_KEY IS NULL OR NEW.MUNICIPIO_KEY <= 0) THEN
        NEW.MUNICIPIO_KEY = GEN_ID(GEN_CAT_MUNICIPIOS, 1);
END;