CREATE GENERATOR GEN_CAT_LAMPARAS;

CREATE TABLE CAT_LAMPARAS (
    LAMPARA_KEY INTEGER NOT NULL PRIMARY KEY,
    CODIGO_LAMPARA VARCHAR(50) NOT NULL,
    DESCRIPCION_LAMPARA VARCHAR(100),
    POTENCIA DECIMAL(6,2),
    VIDA_UTIL_HORAS INTEGER,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_CAT_LAMPARAS_LAMPARA_KEY ON CAT_LAMPARAS (LAMPARA_KEY);
CREATE UNIQUE INDEX IDX_CAT_LAMPARAS_CODIGO_LAMPARA ON CAT_LAMPARAS (CODIGO_LAMPARA);

ALTER TABLE CAT_LAMPARAS ADD CONSTRAINT FK_CAT_LAMPARAS_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CAT_LAMPARAS_BI FOR CAT_LAMPARAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.LAMPARA_KEY IS NULL OR NEW.LAMPARA_KEY <= 0) THEN
        NEW.LAMPARA_KEY = GEN_ID(GEN_CAT_LAMPARAS, 1);
END;