CREATE GENERATOR GEN_CAT_PERFILES;

CREATE TABLE CAT_PERFILES (
    PERFIL_KEY INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CLAVE_PERFIL VARCHAR(100),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_CAT_PERFILES_PERFIL_KEY ON CAT_PERFILES (PERFIL_KEY);
CREATE UNIQUE INDEX IDX_CAT_PERFILES_CLAVE_PERFIL ON CAT_PERFILES (CLAVE_PERFIL);

ALTER TABLE CAT_PERFILES ADD CONSTRAINT FK_CAT_PERFILES_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CAT_PERFILES_BI FOR CAT_PERFILES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.PERFIL_KEY IS NULL OR NEW.PERFIL_KEY <= 0) THEN
        NEW.PERFIL_KEY = GEN_ID(GEN_CAT_PERFILES, 1);
END;