CREATE GENERATOR GEN_CUADRILLA_PROYECTO;

CREATE TABLE CUADRILLA_PROYECTO (
    CUADRILLA_PROYECTO_KEY INTEGER NOT NULL PRIMARY KEY,
    CUADRILLA_LINK INTEGER NOT NULL,
    PROYECTO_LINK INTEGER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_CUADRILLA_PROYECTO_CUADRILLA_PROYECTO_KEY ON CUADRILLA_PROYECTO (CUADRILLA_PROYECTO_KEY);

ALTER TABLE CUADRILLA_PROYECTO ADD CONSTRAINT FK_CUADRILLA_PROYECTO_CUADRILLA 
    FOREIGN KEY (CUADRILLA_LINK) REFERENCES CAT_CUADRILLAS (CUADRILLA_KEY);

ALTER TABLE CUADRILLA_PROYECTO ADD CONSTRAINT FK_CUADRILLA_PROYECTO_PROYECTO 
    FOREIGN KEY (PROYECTO_LINK) REFERENCES CAT_PROYECTOS (PROYECTO_KEY);

ALTER TABLE CUADRILLA_PROYECTO ADD CONSTRAINT FK_CUADRILLA_PROYECTO_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CUADRILLA_PROYECTO_BI FOR CUADRILLA_PROYECTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.CUADRILLA_PROYECTO_KEY IS NULL OR NEW.CUADRILLA_PROYECTO_KEY <= 0) THEN
        NEW.CUADRILLA_PROYECTO_KEY = GEN_ID(GEN_CUADRILLA_PROYECTO, 1);
END;