-- CAT_ESTADOS definition

-- Drop table

-- DROP TABLE CAT_ESTADOS;

CREATE TABLE CAT_ESTADOS (
	ESTADO_KEY INTEGER NOT NULL,
	CLAVE_ESTADO VARCHAR(20),
	NOMBRE VARCHAR(100) NOT NULL,
	NOMBRE_ABREVIADO VARCHAR(100) NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT INTEG_56 PRIMARY KEY (ESTADO_KEY)
);
CREATE UNIQUE INDEX IDX_CAT_ESTADOS_CLAVE_ESTADO ON CAT_ESTADOS (CLAVE_ESTADO);
CREATE UNIQUE INDEX IDX_CAT_ESTADOS_ESTADO_KEY ON CAT_ESTADOS (ESTADO_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY13 ON CAT_ESTADOS (ESTADO_KEY);


-- CAT_ESTATUS definition

-- Drop table

-- DROP TABLE CAT_ESTATUS;

CREATE TABLE CAT_ESTATUS (
	ESTATUS_KEY INTEGER NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT INTEG_2 PRIMARY KEY (ESTATUS_KEY)
);
CREATE UNIQUE INDEX IDX_CAT_ESTATUS_ESTATUS_KEY ON CAT_ESTATUS (ESTATUS_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY1 ON CAT_ESTATUS (ESTATUS_KEY);


-- CAT_ALMACENES definition

-- Drop table

-- DROP TABLE CAT_ALMACENES;

CREATE TABLE CAT_ALMACENES (
	ALMACEN_KEY INTEGER NOT NULL,
	CLAVE_ALMACEN VARCHAR(20),
	NOMBRE VARCHAR(100) NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_48 PRIMARY KEY (ALMACEN_KEY),
	CONSTRAINT FK_CAT_ALMACENES_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY)
);
CREATE INDEX FK_CAT_ALMACENES_ESTATUS ON CAT_ALMACENES (ESTATUS_LINK);
CREATE UNIQUE INDEX IDX_CAT_ALMACENES_ALMACEN_KEY ON CAT_ALMACENES (ALMACEN_KEY);
CREATE UNIQUE INDEX IDX_CAT_ALMACENES_CLAVE_ALMACEN ON CAT_ALMACENES (CLAVE_ALMACEN);
CREATE UNIQUE INDEX RDB$PRIMARY11 ON CAT_ALMACENES (ALMACEN_KEY);


-- CAT_BASES definition

-- Drop table

-- DROP TABLE CAT_BASES;

CREATE TABLE CAT_BASES (
	BASE_KEY INTEGER NOT NULL,
	CODIGO_BASE VARCHAR(50) NOT NULL,
	DESCRIPCION_BASE VARCHAR(100) NOT NULL,
	MATERIAL VARCHAR(50),
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_26 PRIMARY KEY (BASE_KEY),
	CONSTRAINT FK_CAT_BASES_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY)
);
CREATE INDEX FK_CAT_BASES_ESTATUS ON CAT_BASES (ESTATUS_LINK);
CREATE UNIQUE INDEX IDX_CAT_BASES_BASE_KEY ON CAT_BASES (BASE_KEY);
CREATE UNIQUE INDEX IDX_CAT_BASES_CODIGO_BASE ON CAT_BASES (CODIGO_BASE);
CREATE UNIQUE INDEX RDB$PRIMARY6 ON CAT_BASES (BASE_KEY);


-- CAT_BRAZOS definition

-- Drop table

-- DROP TABLE CAT_BRAZOS;

CREATE TABLE CAT_BRAZOS (
	BRAZO_KEY INTEGER NOT NULL,
	CODIGO_BRAZO VARCHAR(50) NOT NULL,
	DESCRIPCION_BRAZO VARCHAR(100),
	MATERIAL VARCHAR(50),
	LONGITUD DECIMAL(5,2),
	ANGULO DECIMAL(5,2),
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_36 PRIMARY KEY (BRAZO_KEY),
	CONSTRAINT FK_CAT_BRAZOS_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY)
);
CREATE INDEX FK_CAT_BRAZOS_ESTATUS ON CAT_BRAZOS (ESTATUS_LINK);
CREATE UNIQUE INDEX IDX_CAT_BRAZOS_BRAZO_KEY ON CAT_BRAZOS (BRAZO_KEY);
CREATE UNIQUE INDEX IDX_CAT_BRAZOS_CODIGO_BRAZO ON CAT_BRAZOS (CODIGO_BRAZO);
CREATE UNIQUE INDEX RDB$PRIMARY8 ON CAT_BRAZOS (BRAZO_KEY);


-- CAT_CUADRILLAS definition

-- Drop table

-- DROP TABLE CAT_CUADRILLAS;

CREATE TABLE CAT_CUADRILLAS (
	CUADRILLA_KEY INTEGER NOT NULL,
	CLAVE_CUADRILLA VARCHAR(20),
	NOMBRE VARCHAR(100) NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_52 PRIMARY KEY (CUADRILLA_KEY),
	CONSTRAINT FK_CAT_CUADRILLAS_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY)
);
CREATE INDEX FK_CAT_CUADRILLAS_ESTATUS ON CAT_CUADRILLAS (ESTATUS_LINK);
CREATE UNIQUE INDEX IDX_CAT_CUADRILLAS_CLAVE_CUADRILLA ON CAT_CUADRILLAS (CLAVE_CUADRILLA);
CREATE UNIQUE INDEX IDX_CAT_CUADRILLAS_CUADRILLA_KEY ON CAT_CUADRILLAS (CUADRILLA_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY12 ON CAT_CUADRILLAS (CUADRILLA_KEY);


-- CAT_LAMPARAS definition

-- Drop table

-- DROP TABLE CAT_LAMPARAS;

CREATE TABLE CAT_LAMPARAS (
	LAMPARA_KEY INTEGER NOT NULL,
	CODIGO_LAMPARA VARCHAR(50) NOT NULL,
	DESCRIPCION_LAMPARA VARCHAR(100),
	POTENCIA DECIMAL(6,2),
	VIDA_UTIL_HORAS INTEGER,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_44 PRIMARY KEY (LAMPARA_KEY),
	CONSTRAINT FK_CAT_LAMPARAS_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY)
);
CREATE INDEX FK_CAT_LAMPARAS_ESTATUS ON CAT_LAMPARAS (ESTATUS_LINK);
CREATE UNIQUE INDEX IDX_CAT_LAMPARAS_CODIGO_LAMPARA ON CAT_LAMPARAS (CODIGO_LAMPARA);
CREATE UNIQUE INDEX IDX_CAT_LAMPARAS_LAMPARA_KEY ON CAT_LAMPARAS (LAMPARA_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY10 ON CAT_LAMPARAS (LAMPARA_KEY);


-- CAT_LUMINARIAS definition

-- Drop table

-- DROP TABLE CAT_LUMINARIAS;

CREATE TABLE CAT_LUMINARIAS (
	ILUMINARIAS_KEY INTEGER NOT NULL PRIMARY KEY,
	CODIGO_LUMINARIA VARCHAR(50) NOT NULL,
	DESCRIPCION_LUMINARIA VARCHAR(100),
	MODELO VARCHAR(100),
	POTENCIA DECIMAL(6,2),
	FLUJO_LUMINOSO DECIMAL(8,2),
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_40 PRIMARY KEY (ILUMINARIAS_KEY),
	CONSTRAINT FK_CAT_LUMINARIAS_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY)
);
CREATE INDEX FK_CAT_LUMINARIAS_ESTATUS ON CAT_LUMINARIAS (ESTATUS_LINK);
CREATE UNIQUE INDEX IDX_CAT_LUMINARIAS_CODIGO_LUMINARIA ON CAT_LUMINARIAS (CODIGO_LUMINARIA);
CREATE UNIQUE INDEX IDX_CAT_LUMINARIAS_ILUMINARIAS_KEY ON CAT_LUMINARIAS (ILUMINARIAS_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY9 ON CAT_LUMINARIAS (ILUMINARIAS_KEY);


-- CAT_MUNICIPIOS definition

-- Drop table

-- DROP TABLE CAT_MUNICIPIOS;

CREATE TABLE CAT_MUNICIPIOS (
	MUNICIPIO_KEY INTEGER NOT NULL,
	ESTADO_LINK INTEGER NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CLAVE_MUNICIPIO VARCHAR(100),
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT INTEG_60 PRIMARY KEY (MUNICIPIO_KEY),
	CONSTRAINT FK_CAT_MUNICIPIOS_ESTATUS FOREIGN KEY (ESTADO_LINK) REFERENCES CAT_ESTADOS(ESTADO_KEY)
);
CREATE INDEX FK_CAT_MUNICIPIOS_ESTATUS ON CAT_MUNICIPIOS (ESTADO_LINK);
CREATE UNIQUE INDEX IDX_CAT_MUNICIPIOS_CLAVE_MUNICIPIO ON CAT_MUNICIPIOS (CLAVE_MUNICIPIO);
CREATE UNIQUE INDEX IDX_CAT_MUNICIPIOS_MUNICIPIO_KEY ON CAT_MUNICIPIOS (MUNICIPIO_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY14 ON CAT_MUNICIPIOS (MUNICIPIO_KEY);


-- CAT_PERFILES definition

-- Drop table

-- DROP TABLE CAT_PERFILES;

CREATE TABLE CAT_PERFILES (
	PERFIL_KEY INTEGER NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CLAVE_PERFIL VARCHAR(100),
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_22 PRIMARY KEY (PERFIL_KEY),
	CONSTRAINT FK_CAT_PERFILES_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY)
);
CREATE INDEX FK_CAT_PERFILES_ESTATUS ON CAT_PERFILES (ESTATUS_LINK);
CREATE UNIQUE INDEX IDX_CAT_PERFILES_CLAVE_PERFIL ON CAT_PERFILES (CLAVE_PERFIL);
CREATE UNIQUE INDEX IDX_CAT_PERFILES_PERFIL_KEY ON CAT_PERFILES (PERFIL_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY5 ON CAT_PERFILES (PERFIL_KEY);


-- CAT_PERMISOS definition

-- Drop table

-- DROP TABLE CAT_PERMISOS;

CREATE TABLE CAT_PERMISOS (
	PERMISO_KEY INTEGER NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	DESCRIPCION VARCHAR(100),
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_18 PRIMARY KEY (PERMISO_KEY),
	CONSTRAINT FK_CAT_PERMISOS_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY)
);
CREATE INDEX FK_CAT_PERMISOS_ESTATUS ON CAT_PERMISOS (ESTATUS_LINK);
CREATE UNIQUE INDEX IDX_CAT_PERMISOS_PERMISO_KEY ON CAT_PERMISOS (PERMISO_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY4 ON CAT_PERMISOS (PERMISO_KEY);


-- CAT_POSTES definition

-- Drop table

-- DROP TABLE CAT_POSTES;

CREATE TABLE CAT_POSTES (
	POSTE_KEY INTEGER NOT NULL,
	DESCRIPCION_POSTE VARCHAR(100) NOT NULL,
	CODIGO_POSTE VARCHAR(50) NOT NULL,
	MATERIAL VARCHAR(50),
	ALTURA DECIMAL(5,2),
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_31 PRIMARY KEY (POSTE_KEY),
	CONSTRAINT FK_CAT_POSTES_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY)
);
CREATE INDEX FK_CAT_POSTES_ESTATUS ON CAT_POSTES (ESTATUS_LINK);
CREATE UNIQUE INDEX IDX_CAT_POSTES_CODIGO_POSTE ON CAT_POSTES (CODIGO_POSTE);
CREATE UNIQUE INDEX IDX_CAT_POSTES_POSTE_KEY ON CAT_POSTES (POSTE_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY7 ON CAT_POSTES (POSTE_KEY);


-- CAT_PROYECTOS definition

-- Drop table

-- DROP TABLE CAT_PROYECTOS;

CREATE TABLE CAT_PROYECTOS (
	PROYECTO_KEY INTEGER NOT NULL,
	CLAVE_PROYECTO VARCHAR(20),
	NOMBRE VARCHAR(200) NOT NULL,
	DESCRIPCION BLOB SUB_TYPE TEXT,
	FECHA_INICIO DATE NOT NULL,
	FECHA_FIN DATE,
	LATITUD DOUBLE PRECISION,
	LONGITUD DOUBLE PRECISION,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	SERVIDOR VARCHAR(20),
	CONSTRAINT INTEG_13 PRIMARY KEY (PROYECTO_KEY),
	CONSTRAINT FK_CAT_PROYECTOS_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY)
);
CREATE INDEX FK_CAT_PROYECTOS_ESTATUS ON CAT_PROYECTOS (ESTATUS_LINK);
CREATE UNIQUE INDEX IDX_CAT_PROYECTOS_CLAVE_PROYECTO ON CAT_PROYECTOS (CLAVE_PROYECTO);
CREATE UNIQUE INDEX IDX_CAT_PROYECTOS_PROYECTO_KEY ON CAT_PROYECTOS (PROYECTO_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY3 ON CAT_PROYECTOS (PROYECTO_KEY);


-- CAT_SERVICIOS_SMTP definition

-- Drop table

-- DROP TABLE CAT_SERVICIOS_SMTP;

CREATE TABLE CAT_SERVICIOS_SMTP (
	SERVICIOS_SMTP_KEY INTEGER NOT NULL,
	SMTP_HOST VARCHAR(30) NOT NULL,
	PUERTO VARCHAR(30) NOT NULL,
	PWD VARCHAR(30) NOT NULL,
	CORREO_REMITENTE VARCHAR(30) NOT NULL,
	PROYECTO_LINK INTEGER NOT NULL,
	ESTATUS_LINK INTEGER NOT NULL,
	CLAVE_PROYECTO_LINK VARCHAR(20),
	CONSTRAINT PK_CAT_SERVICIOS_SMTP PRIMARY KEY (SERVICIOS_SMTP_KEY),
	CONSTRAINT FK_CAT_SERVICIOS_SMTP_1 FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY)
);
CREATE INDEX FK_CAT_SERVICIOS_SMTP_1 ON CAT_SERVICIOS_SMTP (ESTATUS_LINK);


-- CAT_USUARIOS definition

-- Drop table

-- DROP TABLE CAT_USUARIOS;

CREATE TABLE CAT_USUARIOS (
	USUARIOS_KEY INTEGER NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO_PATERNO VARCHAR(100) NOT NULL,
	APELLIDO_MATERNO VARCHAR(100),
	LOGIN VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL,
	TOKEN_PASSWORD VARCHAR(500),
	CLAVE_USUARIO VARCHAR(20),
	PERFIL_LINK INTEGER,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	PWD VARCHAR(500),
	CONSTRAINT INTEG_5 PRIMARY KEY (USUARIOS_KEY),
	CONSTRAINT FK_CAT_USUARIOS_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY),
	CONSTRAINT FK_CAT_USUARIOS_PERFIL FOREIGN KEY (PERFIL_LINK) REFERENCES CAT_PERFILES(PERFIL_KEY)
);
CREATE INDEX FK_CAT_USUARIOS_ESTATUS ON CAT_USUARIOS (ESTATUS_LINK);
CREATE INDEX FK_CAT_USUARIOS_PERFIL ON CAT_USUARIOS (PERFIL_LINK);
CREATE UNIQUE INDEX IDX_CAT_USUARIOS_CLAVE_USUARIO ON CAT_USUARIOS (CLAVE_USUARIO);
CREATE UNIQUE INDEX IDX_CAT_USUARIOS_EMAIL ON CAT_USUARIOS (EMAIL);
CREATE UNIQUE INDEX IDX_CAT_USUARIOS_LOGIN ON CAT_USUARIOS (LOGIN);
CREATE UNIQUE INDEX IDX_CAT_USUARIOS_USUARIOS_KEY ON CAT_USUARIOS (USUARIOS_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY2 ON CAT_USUARIOS (USUARIOS_KEY);


-- CUADRILLA_PROYECTO definition

-- Drop table

-- DROP TABLE CUADRILLA_PROYECTO;

CREATE TABLE CUADRILLA_PROYECTO (
	CUADRILLA_PROYECTO_KEY INTEGER NOT NULL,
	CUADRILLA_LINK INTEGER NOT NULL,
	PROYECTO_LINK INTEGER NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_73 PRIMARY KEY (CUADRILLA_PROYECTO_KEY),
	CONSTRAINT FK_CUADRILLA_PROYECTO_CUADRILLA FOREIGN KEY (CUADRILLA_LINK) REFERENCES CAT_CUADRILLAS(CUADRILLA_KEY),
	CONSTRAINT FK_CUADRILLA_PROYECTO_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY),
	CONSTRAINT FK_CUADRILLA_PROYECTO_PROYECTO FOREIGN KEY (PROYECTO_LINK) REFERENCES CAT_PROYECTOS(PROYECTO_KEY)
);
CREATE INDEX FK_CUADRILLA_PROYECTO_CUADRILLA ON CUADRILLA_PROYECTO (CUADRILLA_LINK);
CREATE INDEX FK_CUADRILLA_PROYECTO_ESTATUS ON CUADRILLA_PROYECTO (ESTATUS_LINK);
CREATE INDEX FK_CUADRILLA_PROYECTO_PROYECTO ON CUADRILLA_PROYECTO (PROYECTO_LINK);
CREATE UNIQUE INDEX IDX_CUADRILLA_PROYECTO_CUADRILLA_PROYECTO_KEY ON CUADRILLA_PROYECTO (CUADRILLA_PROYECTO_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY17 ON CUADRILLA_PROYECTO (CUADRILLA_PROYECTO_KEY);


-- PERFIL_PERMISO definition

-- Drop table

-- DROP TABLE PERFIL_PERMISO;

CREATE TABLE PERFIL_PERMISO (
	PERFIL_PERMISO_KEY INTEGER NOT NULL,
	PERFIL_LINK INTEGER NOT NULL,
	PERMISO_LINK INTEGER NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_88 PRIMARY KEY (PERFIL_PERMISO_KEY),
	CONSTRAINT FK_PERFIL_PERMISO_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY),
	CONSTRAINT FK_PERFIL_PERMISO_PERFIL FOREIGN KEY (PERFIL_LINK) REFERENCES CAT_PERFILES(PERFIL_KEY),
	CONSTRAINT FK_PERFIL_PERMISO_PERMISO FOREIGN KEY (PERMISO_LINK) REFERENCES CAT_PERMISOS(PERMISO_KEY)
);
CREATE INDEX FK_PERFIL_PERMISO_ESTATUS ON PERFIL_PERMISO (ESTATUS_LINK);
CREATE INDEX FK_PERFIL_PERMISO_PERFIL ON PERFIL_PERMISO (PERFIL_LINK);
CREATE INDEX FK_PERFIL_PERMISO_PERMISO ON PERFIL_PERMISO (PERMISO_LINK);
CREATE UNIQUE INDEX IDX_PERFIL_PERMISO_PERFIL_PERMISO_KEY ON PERFIL_PERMISO (PERFIL_PERMISO_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY20 ON PERFIL_PERMISO (PERFIL_PERMISO_KEY);


-- USUARIO_PROYECTO definition

-- Drop table

-- DROP TABLE USUARIO_PROYECTO;

CREATE TABLE USUARIO_PROYECTO (
	USUARIO_PROYECTO_KEY INTEGER NOT NULL,
	USUARIO_LINK INTEGER NOT NULL,
	PROYECTO_LINK INTEGER NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_78 PRIMARY KEY (USUARIO_PROYECTO_KEY),
	CONSTRAINT FK_USUARIO_PROYECTO_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY),
	CONSTRAINT FK_USUARIO_PROYECTO_PROYECTO FOREIGN KEY (PROYECTO_LINK) REFERENCES CAT_PROYECTOS(PROYECTO_KEY),
	CONSTRAINT FK_USUARIO_PROYECTO_USUARIO FOREIGN KEY (USUARIO_LINK) REFERENCES CAT_USUARIOS(USUARIOS_KEY)
);
CREATE INDEX FK_USUARIO_PROYECTO_ESTATUS ON USUARIO_PROYECTO (ESTATUS_LINK);
CREATE INDEX FK_USUARIO_PROYECTO_PROYECTO ON USUARIO_PROYECTO (PROYECTO_LINK);
CREATE INDEX FK_USUARIO_PROYECTO_USUARIO ON USUARIO_PROYECTO (USUARIO_LINK);
CREATE UNIQUE INDEX IDX_USUARIO_PROYECTO_USUARIO_PROYECTO_KEY ON USUARIO_PROYECTO (USUARIO_PROYECTO_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY18 ON USUARIO_PROYECTO (USUARIO_PROYECTO_KEY);


-- ALMACEN_PROYECTO definition

-- Drop table

-- DROP TABLE ALMACEN_PROYECTO;

CREATE TABLE ALMACEN_PROYECTO (
	ALMACEN_PROYECTO_KEY INTEGER NOT NULL,
	ALMACEN_LINK INTEGER NOT NULL,
	PROYECTO_LINK INTEGER NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ESTATUS_LINK INTEGER NOT NULL,
	CONSTRAINT INTEG_68 PRIMARY KEY (ALMACEN_PROYECTO_KEY),
	CONSTRAINT FK_ALMACEN_PROYECTO_ALMACEN FOREIGN KEY (ALMACEN_LINK) REFERENCES CAT_ALMACENES(ALMACEN_KEY),
	CONSTRAINT FK_ALMACEN_PROYECTO_ESTATUS FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS(ESTATUS_KEY),
	CONSTRAINT FK_ALMACEN_PROYECTO_PROYECTO FOREIGN KEY (PROYECTO_LINK) REFERENCES CAT_PROYECTOS(PROYECTO_KEY)
);
CREATE INDEX FK_ALMACEN_PROYECTO_ALMACEN ON ALMACEN_PROYECTO (ALMACEN_LINK);
CREATE INDEX FK_ALMACEN_PROYECTO_ESTATUS ON ALMACEN_PROYECTO (ESTATUS_LINK);
CREATE INDEX FK_ALMACEN_PROYECTO_PROYECTO ON ALMACEN_PROYECTO (PROYECTO_LINK);
CREATE UNIQUE INDEX IDX_ALMACEN_PROYECTO_ALMACEN_PROYECTO_KEY ON ALMACEN_PROYECTO (ALMACEN_PROYECTO_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY16 ON ALMACEN_PROYECTO (ALMACEN_PROYECTO_KEY);


-- CAT_LOCALIDADES definition

-- Drop table

-- DROP TABLE CAT_LOCALIDADES;

CREATE TABLE CAT_LOCALIDADES (
	LOCALIDAD_KEY INTEGER NOT NULL,
	MUNICIPIO_LINK INTEGER NOT NULL,
	CLAVE_LOCALIDAD VARCHAR(100),
	NOMBRE VARCHAR(100) NOT NULL,
	CP VARCHAR(6),
	LATITUD DOUBLE PRECISION,
	LONGITUD DOUBLE PRECISION,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT INTEG_64 PRIMARY KEY (LOCALIDAD_KEY),
	CONSTRAINT FK_CAT_LOCALIDADES_MUNICIPIO FOREIGN KEY (MUNICIPIO_LINK) REFERENCES CAT_MUNICIPIOS(MUNICIPIO_KEY)
);
CREATE INDEX FK_CAT_LOCALIDADES_MUNICIPIO ON CAT_LOCALIDADES (MUNICIPIO_LINK);
CREATE UNIQUE INDEX IDX_CAT_LOCALIDADES_CLAVE_LOCALIDAD ON CAT_LOCALIDADES (CLAVE_LOCALIDAD);
CREATE UNIQUE INDEX IDX_CAT_LOCALIDADES_LOCALIDAD_KEY ON CAT_LOCALIDADES (LOCALIDAD_KEY);
CREATE UNIQUE INDEX RDB$PRIMARY15 ON CAT_LOCALIDADES (LOCALIDAD_KEY);