CREATE GENERATOR GEN_PERFIL_PERMISO;

CREATE TABLE PERFIL_PERMISO (
    PERFIL_PERMISO_KEY INTEGER NOT NULL PRIMARY KEY,
    PERFIL_LINK INTEGER NOT NULL,
    PERMISO_LINK INTEGER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_PERFIL_PERMISO_PERFIL_PERMISO_KEY ON PERFIL_PERMISO (PERFIL_PERMISO_KEY);

ALTER TABLE PERFIL_PERMISO ADD CONSTRAINT FK_PERFIL_PERMISO_PERFIL 
    FOREIGN KEY (PERFIL_LINK) REFERENCES CAT_PERFILES (PERFIL_KEY);

ALTER TABLE PERFIL_PERMISO ADD CONSTRAINT FK_PERFIL_PERMISO_PERMISO 
    FOREIGN KEY (PERMISO_LINK) REFERENCES CAT_PERMISOS (PERMISO_KEY);

ALTER TABLE PERFIL_PERMISO ADD CONSTRAINT FK_PERFIL_PERMISO_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_PERFIL_PERMISO_BI FOR PERFIL_PERMISO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.PERFIL_PERMISO_KEY IS NULL OR NEW.PERFIL_PERMISO_KEY <= 0) THEN
        NEW.PERFIL_PERMISO_KEY = GEN_ID(GEN_PERFIL_PERMISO, 1);
END;