CREATE GENERATOR GEN_USUARIO_PERFIL;

CREATE TABLE USUARIO_PERFIL (
    USUARIO_PERFIL_KEY INTEGER NOT NULL PRIMARY KEY,
    USUARIO_LINK INTEGER NOT NULL,
    PERFIL_LINK INTEGER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_USUARIO_PERFIL_USUARIO_PERFIL_KEY ON USUARIO_PERFIL (USUARIO_PERFIL_KEY);

ALTER TABLE USUARIO_PERFIL ADD CONSTRAINT FK_USUARIO_PERFIL_USUARIO 
    FOREIGN KEY (USUARIO_LINK) REFERENCES CAT_USUARIOS (USUARIOS_KEY);

ALTER TABLE USUARIO_PERFIL ADD CONSTRAINT FK_USUARIO_PERFIL_PERFIL 
    FOREIGN KEY (PERFIL_LINK) REFERENCES CAT_PERFILES (PERFIL_KEY);

ALTER TABLE USUARIO_PERFIL ADD CONSTRAINT FK_USUARIO_PERFIL_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_USUARIO_PERFIL_BI FOR USUARIO_PERFIL
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.USUARIO_PERFIL_KEY IS NULL OR NEW.USUARIO_PERFIL_KEY <= 0) THEN
        NEW.USUARIO_PERFIL_KEY = GEN_ID(GEN_USUARIO_PERFIL, 1);
END;