CREATE GENERATOR GEN_USUARIO_PROYECTO;

CREATE TABLE USUARIO_PROYECTO (
    USUARIO_PROYECTO_KEY INTEGER NOT NULL PRIMARY KEY,
    USUARIO_LINK INTEGER NOT NULL,
    PROYECTO_LINK INTEGER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_USUARIO_PROYECTO_USUARIO_PROYECTO_KEY ON USUARIO_PROYECTO (USUARIO_PROYECTO_KEY);

ALTER TABLE USUARIO_PROYECTO ADD CONSTRAINT FK_USUARIO_PROYECTO_USUARIO 
    FOREIGN KEY (USUARIO_LINK) REFERENCES CAT_USUARIOS (USUARIOS_KEY);

ALTER TABLE USUARIO_PROYECTO ADD CONSTRAINT FK_USUARIO_PROYECTO_PROYECTO 
    FOREIGN KEY (PROYECTO_LINK) REFERENCES CAT_PROYECTOS (PROYECTO_KEY);

ALTER TABLE USUARIO_PROYECTO ADD CONSTRAINT FK_USUARIO_PROYECTO_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_USUARIO_PROYECTO_BI FOR USUARIO_PROYECTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.USUARIO_PROYECTO_KEY IS NULL OR NEW.USUARIO_PROYECTO_KEY <= 0) THEN
        NEW.USUARIO_PROYECTO_KEY = GEN_ID(GEN_USUARIO_PROYECTO, 1);
END;