CREATE GENERATOR GEN_ALMACEN_PROYECTO;

CREATE TABLE ALMACEN_PROYECTO (
    ALMACEN_PROYECTO_KEY INTEGER NOT NULL PRIMARY KEY,
    ALMACEN_LINK INTEGER NOT NULL,
    PROYECTO_LINK INTEGER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_ALMACEN_PROYECTO_ALMACEN_PROYECTO_KEY ON ALMACEN_PROYECTO (ALMACEN_PROYECTO_KEY);

ALTER TABLE ALMACEN_PROYECTO ADD CONSTRAINT FK_ALMACEN_PROYECTO_ALMACEN 
    FOREIGN KEY (ALMACEN_LINK) REFERENCES CAT_ALMACENES (ALMACEN_KEY);

ALTER TABLE ALMACEN_PROYECTO ADD CONSTRAINT FK_ALMACEN_PROYECTO_PROYECTO 
    FOREIGN KEY (PROYECTO_LINK) REFERENCES CAT_PROYECTOS (PROYECTO_KEY);

ALTER TABLE ALMACEN_PROYECTO ADD CONSTRAINT FK_ALMACEN_PROYECTO_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_ALMACEN_PROYECTO_BI FOR ALMACEN_PROYECTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ALMACEN_PROYECTO_KEY IS NULL OR NEW.ALMACEN_PROYECTO_KEY <= 0) THEN
        NEW.ALMACEN_PROYECTO_KEY = GEN_ID(GEN_ALMACEN_PROYECTO, 1);
END;