CREATE GENERATOR GEN_CAT_PROYECTOS;

CREATE TABLE CAT_PROYECTOS (
    PROYECTO_KEY INTEGER NOT NULL PRIMARY KEY,
    CLAVE_PROYECTO VARCHAR(20),
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION BLOB SUB_TYPE TEXT,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    LATITUD DOUBLE PRECISION,
    LONGITUD DOUBLE PRECISION,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL,
    SERVIDOR VARCHAR(20)
);

CREATE UNIQUE INDEX IDX_CAT_PROYECTOS_PROYECTO_KEY ON CAT_PROYECTOS (PROYECTO_KEY);
CREATE UNIQUE INDEX IDX_CAT_PROYECTOS_CLAVE_PROYECTO ON CAT_PROYECTOS (CLAVE_PROYECTO);

ALTER TABLE CAT_PROYECTOS ADD CONSTRAINT FK_CAT_PROYECTOS_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CAT_PROYECTOS_BI FOR CAT_PROYECTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.PROYECTO_KEY IS NULL OR NEW.PROYECTO_KEY <= 0) THEN
        NEW.PROYECTO_KEY = GEN_ID(GEN_CAT_PROYECTOS, 1);
END;