CREATE GENERATOR GEN_CAT_TEMPLATES;

CREATE TABLE CAT_TEMPLATES
(
    TEMPLATE_KEY INTEGER NOT NULL PRIMARY KEY,
    PROYECTO_LINK INTEGER NOT NULL,
    ASUNTO VARCHAR(250)
    DESCRIPCION VARCHAR(200) NOT NULL,
    CODIGO TEXT NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_CAT_TEMPLATES_TEMPLATE_KEY ON CAT_TEMPLATES (TEMPLATE_KEY);
CREATE UNIQUE INDEX IDX_CAT_TEMPLATES_PROYECTO_LINK ON CAT_TEMPLATES (PROYECTO_LINK);

ALTER TABLE CAT_TEMPLATES ADD CONSTRAINT FK_CAT_TEMPLATES_PROYECTO 
    FOREIGN KEY (PROYECTO_LINK) REFERENCES CAT_PROYECTOS (PROYECTO_KEY);

ALTER TABLE CAT_TEMPLATES ADD CONSTRAINT FK_CAT_TEMPLATES_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CAT_TEMPLATES_BI FOR CAT_TEMPLATES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.TEMPLATE_KEY IS NULL OR NEW.TEMPLATE_KEY <= 0) THEN
        NEW.TEMPLATE_KEY = GEN_ID(GEN_CAT_TEMPLATES, 1);
END;