CREATE GENERATOR GEN_CAT_LOCALIDADES;

CREATE TABLE CAT_LOCALIDADES (
    LOCALIDAD_KEY INTEGER NOT NULL PRIMARY KEY,
    MUNICIPIO_LINK INTEGER NOT NULL,
    CLAVE_LOCALIDAD VARCHAR(100),
    NOMBRE VARCHAR(100) NOT NULL,
    CP VARCHAR(6),
    LATITUD DOUBLE PRECISION,
    LONGITUD DOUBLE PRECISION,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IDX_CAT_LOCALIDADES_LOCALIDAD_KEY ON CAT_LOCALIDADES (LOCALIDAD_KEY);
CREATE UNIQUE INDEX IDX_CAT_LOCALIDADES_CLAVE_LOCALIDAD ON CAT_LOCALIDADES (CLAVE_LOCALIDAD);

ALTER TABLE CAT_LOCALIDADES ADD CONSTRAINT FK_CAT_LOCALIDADES_MUNICIPIO 
    FOREIGN KEY (MUNICIPIO_LINK) REFERENCES CAT_MUNICIPIOS (MUNICIPIO_KEY);

CREATE TRIGGER TR_CAT_LOCALIDADES_BI FOR CAT_LOCALIDADES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.LOCALIDAD_KEY IS NULL OR NEW.LOCALIDAD_KEY <= 0) THEN
        NEW.LOCALIDAD_KEY = GEN_ID(GEN_CAT_LOCALIDADES, 1);
END;