CREATE GENERATOR GEN_CAT_POSTES;

CREATE TABLE CAT_POSTES (
    POSTE_KEY INTEGER NOT NULL PRIMARY KEY,
    DESCRIPCION_POSTE VARCHAR(100) NOT NULL,
    CODIGO_POSTE VARCHAR(50) NOT NULL,
    MATERIAL VARCHAR(50),
    ALTURA DECIMAL(5,2),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_CAT_POSTES_POSTE_KEY ON CAT_POSTES (POSTE_KEY);
CREATE UNIQUE INDEX IDX_CAT_POSTES_CODIGO_POSTE ON CAT_POSTES (CODIGO_POSTE);

ALTER TABLE CAT_POSTES ADD CONSTRAINT FK_CAT_POSTES_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CAT_POSTES_BI FOR CAT_POSTES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.POSTE_KEY IS NULL OR NEW.POSTE_KEY <= 0) THEN
        NEW.POSTE_KEY = GEN_ID(GEN_CAT_POSTES, 1);
END;