CREATE GENERATOR GEN_CAT_BRAZOS;

CREATE TABLE CAT_BRAZOS (
    BRAZO_KEY INTEGER NOT NULL PRIMARY KEY,
    CODIGO_BRAZO VARCHAR(50) NOT NULL,
    DESCRIPCION_BRAZO VARCHAR(100),
    MATERIAL VARCHAR(50),
    LONGITUD DECIMAL(5,2),
    ANGULO DECIMAL(5,2),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_CAT_BRAZOS_BRAZO_KEY ON CAT_BRAZOS (BRAZO_KEY);
CREATE UNIQUE INDEX IDX_CAT_BRAZOS_CODIGO_BRAZO ON CAT_BRAZOS (CODIGO_BRAZO);

ALTER TABLE CAT_BRAZOS ADD CONSTRAINT FK_CAT_BRAZOS_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CAT_BRAZOS_BI FOR CAT_BRAZOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.BRAZO_KEY IS NULL OR NEW.BRAZO_KEY <= 0) THEN
        NEW.BRAZO_KEY = GEN_ID(GEN_CAT_BRAZOS, 1);
END;