CREATE GENERATOR GEN_CAT_PERMISOS;

CREATE TABLE CAT_PERMISOS (
    PERMISO_KEY INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(100),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_CAT_PERMISOS_PERMISO_KEY ON CAT_PERMISOS (PERMISO_KEY);

ALTER TABLE CAT_PERMISOS ADD CONSTRAINT FK_CAT_PERMISOS_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CAT_PERMISOS_BI FOR CAT_PERMISOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.PERMISO_KEY IS NULL OR NEW.PERMISO_KEY <= 0) THEN
        NEW.PERMISO_KEY = GEN_ID(GEN_CAT_PERMISOS, 1);
END;