CREATE GENERATOR GEN_CAT_LUMINARIAS;

CREATE TABLE CAT_LUMINARIAS (
    ILUMINARIAS_KEY INTEGER NOT NULL PRIMARY KEY,
    CODIGO_LUMINARIA VARCHAR(50) NOT NULL,
    DESCRIPCION_LUMINARIA VARCHAR(100),
    MODELO VARCHAR(100),
    POTENCIA DECIMAL(6,2),
    FLUJO_LUMINOSO DECIMAL(8,2),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_CAT_LUMINARIAS_ILUMINARIAS_KEY ON CAT_LUMINARIAS (ILUMINARIAS_KEY);
CREATE UNIQUE INDEX IDX_CAT_LUMINARIAS_CODIGO_LUMINARIA ON CAT_LUMINARIAS (CODIGO_LUMINARIA);

ALTER TABLE CAT_LUMINARIAS ADD CONSTRAINT FK_CAT_LUMINARIAS_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

CREATE TRIGGER TR_CAT_LUMINARIAS_BI FOR CAT_LUMINARIAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ILUMINARIAS_KEY IS NULL OR NEW.ILUMINARIAS_KEY <= 0) THEN
        NEW.ILUMINARIAS_KEY = GEN_ID(GEN_CAT_LUMINARIAS, 1);
END;