CREATE GENERATOR GEN_CAT_USUARIOS;

CREATE TABLE CAT_USUARIOS (
    USUARIOS_KEY INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR(100),
    LOGIN VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    PWD VARCHAR(255) NOT NULL,
    TOKEN_PASSWORD VARCHAR(500),
    CLAVE_USUARIO VARCHAR(20),
    PERFIL_LINK INTEGER,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTATUS_LINK INTEGER NOT NULL
);

CREATE UNIQUE INDEX IDX_CAT_USUARIOS_USUARIOS_KEY ON CAT_USUARIOS (USUARIOS_KEY);
CREATE UNIQUE INDEX IDX_CAT_USUARIOS_LOGIN ON CAT_USUARIOS (LOGIN);
CREATE UNIQUE INDEX IDX_CAT_USUARIOS_EMAIL ON CAT_USUARIOS (EMAIL);
CREATE UNIQUE INDEX IDX_CAT_USUARIOS_CLAVE_USUARIO ON CAT_USUARIOS (CLAVE_USUARIO);

ALTER TABLE CAT_USUARIOS ADD CONSTRAINT FK_CAT_USUARIOS_ESTATUS 
    FOREIGN KEY (ESTATUS_LINK) REFERENCES CAT_ESTATUS (ESTATUS_KEY);

ALTER TABLE CAT_USUARIOS ADD CONSTRAINT FK_CAT_USUARIOS_PERFIL 
    FOREIGN KEY (PERFIL_LINK) REFERENCES CAT_PERFILES (PERFIL_KEY);

CREATE TRIGGER TR_CAT_USUARIOS_BI FOR CAT_USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.USUARIOS_KEY IS NULL OR NEW.USUARIOS_KEY <= 0) THEN
        NEW.USUARIOS_KEY = GEN_ID(GEN_CAT_USUARIOS, 1);
END;