CREATE OR ALTER PROCEDURE CTLIGHT_GET_SMTP_X_COD_PROYECTO (P_CODIGO_PROYECTO VARCHAR(30))
RETURNS (
	SMTP_HOST VARCHAR(30),
	PUERTO VARCHAR(30),
	PWD VARCHAR(30),
	CORREO_REMITENTE VARCHAR(30),
	PROYECTO_LINK INTEGER,
	ESTATUS_LINK INTEGER,
	CLAVE_PROYECTO_LINK VARCHAR(20)
)
AS
begin
  for select SMTP_HOST, CSS.PUERTO, CSS.PWD, CSS.CORREO_REMITENTE, CSS.PROYECTO_LINK, CSS.ESTATUS_LINK,
             CSS.CLAVE_PROYECTO_LINK
      from CAT_SERVICIOS_SMTP CSS
      join CAT_PROYECTOS CP on CP.CLAVE_PROYECTO = CSS.CLAVE_PROYECTO_LINK
      where CSS.CLAVE_PROYECTO_LINK = :P_CODIGO_PROYECTO
      into :SMTP_HOST, :PUERTO, :PWD, :CORREO_REMITENTE, :PROYECTO_LINK, :ESTATUS_LINK, :CLAVE_PROYECTO_LINK
  do
  begin
    suspend;
  end
end;