SET TERM ^ ;

CREATE OR ALTER PROCEDURE CTLIGHT_SET_CAT_BRAZOS (
    P_BRAZO_KEY INTEGER,
    P_CODIGO_BRAZO VARCHAR(50),
    P_DESCRIPCION_BRAZO VARCHAR(100),
    P_MATERIAL VARCHAR(50),
    P_LONGITUD DECIMAL(5,2),
    P_ANGULO DECIMAL(5,2),
    P_ESTATUS_LINK INTEGER
)
RETURNS (
    BRAZO_KEY INTEGER,
    RESULTADO INTEGER,
    MSG VARCHAR(100)
)
AS
DECLARE VARIABLE V_BRAZO_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
    V_CODE = 0;
    V_MSG = '';
    V_BRAZO_KEY = 0;

    IF (:P_BRAZO_KEY = 0) THEN
    BEGIN
		INSERT INTO CAT_BRAZOS (CODIGO_BRAZO, DESCRIPCION_BRAZO, MATERIAL, LONGITUD, ANGULO, ESTATUS_LINK)
		VALUES (:P_CODIGO_BRAZO, :P_DESCRIPCION_BRAZO, :P_MATERIAL, :P_LONGITUD, :P_ANGULO, :P_ESTATUS_LINK)
		RETURNING BRAZO_KEY INTO :V_BRAZO_KEY;
    END
    ELSE IF (:P_BRAZO_KEY > 0) THEN
    BEGIN
		IF (NOT EXISTS(SELECT BRAZO_KEY
				FROM CAT_BRAZOS
				WHERE (BRAZO_KEY = :P_BRAZO_KEY))) THEN
		BEGIN
			V_MSG = 'No existe un registro con este key';
		END
        UPDATE CAT_BRAZOS
        SET DESCRIPCION_BRAZO = :P_DESCRIPCION_BRAZO,
            CODIGO_BRAZO = :P_CODIGO_BRAZO,
            MATERIAL = :P_MATERIAL,
            LONGITUD = :P_LONGITUD,
            ANGULO = :P_ANGULO,
            ESTATUS_LINK = :P_ESTATUS_LINK,
            FECHA_MODIFICACION = CURRENT_TIMESTAMP
        WHERE BRAZO_KEY = :P_BRAZO_KEY;
    END

    IF (ROW_COUNT > 0) THEN
    BEGIN
        V_CODE = 1;
        V_MSG = 'Información guardada correctamente';
    END
    ELSE
    BEGIN
        V_CODE = 0;
        V_MSG = 'No se pudo guardar la información';
    END

    RESULTADO = V_CODE;
    BRAZO_KEY = V_BRAZO_KEY;
    MSG = V_MSG;
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_DEL_CAT_BRAZOS (
    P_BRAZO_KEY INTEGER
)
RETURNS (
    BRAZO_KEY INTEGER,
    RESULTADO INTEGER,
    MSG VARCHAR(100)
)
AS
DECLARE VARIABLE V_BRAZO_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
    V_CODE = 0;
    V_MSG = '';
    V_BRAZO_KEY = 0;

    IF (NOT EXISTS(SELECT BRAZO_KEY
		FROM CAT_BRAZOS
		WHERE (BRAZO_KEY = :P_BRAZO_KEY))) THEN
	BEGIN
		V_MSG = 'No existe un registro con este key';
	END

    UPDATE CAT_BRAZOS
    SET ESTATUS_LINK = 2,
        FECHA_MODIFICACION = CURRENT_TIMESTAMP
    WHERE BRAZO_KEY = :P_BRAZO_KEY;
    IF (ROW_COUNT > 0) THEN
    BEGIN
        V_CODE = 1;
        V_MSG = 'Registro eliminado correctamente';
    END
    ELSE
    BEGIN
        V_CODE = 0;
        V_MSG = 'No se pudo eliminar el registro';
    END
    RESULTADO = V_CODE;
    BRAZO_KEY = V_BRAZO_KEY;
    MSG = V_MSG;
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_GET_CAT_BRAZOS (
    P_BRAZO_KEY INTEGER = 0,
    P_ONLY_ACTIVE SMALLINT = 0
)
RETURNS (
    BRAZO_KEY INTEGER,
    CODIGO_BRAZO VARCHAR(50),
    DESCRIPCION_BRAZO VARCHAR(100),
    MATERIAL VARCHAR(50),
    LONGITUD DECIMAL(5,2),
    ANGULO DECIMAL(5,2),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ESTATUS_LINK INTEGER
)
AS
BEGIN
    IF (:P_BRAZO_KEY = 0) THEN
    BEGIN
        -- Retornar listado completo
        FOR
            SELECT BRAZO_KEY, CODIGO_BRAZO, DESCRIPCION_BRAZO, MATERIAL, LONGITUD, ANGULO, FECHA_CREACION, FECHA_MODIFICACION, ESTATUS_LINK
            FROM CAT_BRAZOS
            WHERE (:P_ONLY_ACTIVE = 0 OR ESTATUS_LINK = 1)
            INTO :BRAZO_KEY, :CODIGO_BRAZO, :DESCRIPCION_BRAZO, :MATERIAL, :LONGITUD, :ANGULO, :FECHA_CREACION, :FECHA_MODIFICACION, :ESTATUS_LINK
        DO
            SUSPEND;
    END
    ELSE IF (:P_BRAZO_KEY > 0) THEN
    BEGIN
        -- Retornar solo un registro específico
        FOR
            SELECT BRAZO_KEY, CODIGO_BRAZO, DESCRIPCION_BRAZO, MATERIAL, LONGITUD, ANGULO, FECHA_CREACION, FECHA_MODIFICACION, ESTATUS_LINK
            FROM CAT_BRAZOS
            WHERE BRAZO_KEY = :P_BRAZO_KEY
            INTO :BRAZO_KEY, :CODIGO_BRAZO, :DESCRIPCION_BRAZO, :MATERIAL, :LONGITUD, :ANGULO, :FECHA_CREACION, :FECHA_MODIFICACION, :ESTATUS_LINK
        DO
            SUSPEND;
    END
END^

SET TERM ; ^