SET TERM ^ ;

CREATE OR ALTER PROCEDURE CTLIGHT_SET_CAT_LUMINARIAS (
    P_ILUMINARIAS_KEY INTEGER,
    P_CODIGO_LUMINARIA VARCHAR(50),
    P_DESCRIPCION_LUMINARIA VARCHAR(100),
    P_MODELO VARCHAR(100),
    P_POTENCIA DECIMAL(6,2),
    P_FLUJO_LUMINOSO DECIMAL(8,2),
    P_ESTATUS_LINK INTEGER
)
RETURNS (
    ILUMINARIAS_KEY INTEGER,
    RESULTADO INTEGER,
    MSG VARCHAR(100)
)
AS
DECLARE VARIABLE V_ILUMINARIAS_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
    V_CODE = 0;
    V_MSG = '';
    V_ILUMINARIAS_KEY = 0;

    IF (:P_ILUMINARIAS_KEY = 0) THEN
    BEGIN
		INSERT INTO CAT_LUMINARIAS (CODIGO_LUMINARIA, DESCRIPCION_LUMINARIA, MODELO, POTENCIA, FLUJO_LUMINOSO, ESTATUS_LINK)
		VALUES (:P_CODIGO_LUMINARIA, :P_DESCRIPCION_LUMINARIA, :P_MODELO, :P_POTENCIA, :P_FLUJO_LUMINOSO, :P_ESTATUS_LINK)
		RETURNING ILUMINARIAS_KEY INTO :V_ILUMINARIAS_KEY;
    END
    ELSE IF (:P_ILUMINARIAS_KEY > 0) THEN
    BEGIN
		IF (NOT EXISTS(SELECT ILUMINARIAS_KEY
				FROM CAT_LUMINARIAS
				WHERE (ILUMINARIAS_KEY = :P_ILUMINARIAS_KEY))) THEN
		BEGIN
			V_MSG = 'No existe un registro con este key';
		END
        UPDATE CAT_LUMINARIAS
        SET DESCRIPCION_LUMINARIA = :P_DESCRIPCION_LUMINARIA,
            CODIGO_LUMINARIA = :P_CODIGO_LUMINARIA,
            MODELO = :P_MODELO,
            POTENCIA = :P_POTENCIA,
            FLUJO_LUMINOSO = :P_FLUJO_LUMINOSO,
            ESTATUS_LINK = :P_ESTATUS_LINK,
            FECHA_MODIFICACION = CURRENT_TIMESTAMP
        WHERE ILUMINARIAS_KEY = :P_ILUMINARIAS_KEY;
    END

    IF (ROW_COUNT > 0) THEN
    BEGIN
        V_CODE = 1;
        V_MSG = 'Información guardada correctamente';
    END
    ELSE
    BEGIN
        V_CODE = 0;
        V_MSG = 'No se pudo guardar la información';
    END

    RESULTADO = V_CODE;
    ILUMINARIAS_KEY = V_ILUMINARIAS_KEY;
    MSG = V_MSG;
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_DEL_CAT_LUMINARIAS (
    P_ILUMINARIAS_KEY INTEGER
)
RETURNS (
    ILUMINARIAS_KEY INTEGER,
    RESULTADO INTEGER,
    MSG VARCHAR(100)
)
AS
DECLARE VARIABLE V_ILUMINARIAS_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
    V_CODE = 0;
    V_MSG = '';
    V_ILUMINARIAS_KEY = 0;

    IF (NOT EXISTS(SELECT ILUMINARIAS_KEY
		FROM CAT_LUMINARIAS
		WHERE (ILUMINARIAS_KEY = :P_ILUMINARIAS_KEY))) THEN
	BEGIN
		V_MSG = 'No existe un registro con este key';
	END

    UPDATE CAT_LUMINARIAS
    SET ESTATUS_LINK = 2,
        FECHA_MODIFICACION = CURRENT_TIMESTAMP
    WHERE ILUMINARIAS_KEY = :P_ILUMINARIAS_KEY;
    IF (ROW_COUNT > 0) THEN
    BEGIN
        V_CODE = 1;
        V_MSG = 'Registro eliminado correctamente';
    END
    ELSE
    BEGIN
        V_CODE = 0;
        V_MSG = 'No se pudo eliminar el registro';
    END
    RESULTADO = V_CODE;
    ILUMINARIAS_KEY = V_ILUMINARIAS_KEY;
    MSG = V_MSG;
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_GET_CAT_LUMINARIAS (
    P_ILUMINARIAS_KEY INTEGER = 0,
    P_ONLY_ACTIVE SMALLINT = 0
)
RETURNS (
    ILUMINARIAS_KEY INTEGER,
    CODIGO_LUMINARIA VARCHAR(50),
    DESCRIPCION_LUMINARIA VARCHAR(100),
    MODELO VARCHAR(100),
    POTENCIA DECIMAL(6,2),
    FLUJO_LUMINOSO DECIMAL(8,2),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    ESTATUS_LINK INTEGER
)
AS
BEGIN
    IF (:P_ILUMINARIAS_KEY = 0) THEN
    BEGIN
        -- Retornar listado completo
        FOR
            SELECT ILUMINARIAS_KEY, CODIGO_LUMINARIA, DESCRIPCION_LUMINARIA, MODELO, POTENCIA, FLUJO_LUMINOSO, FECHA_CREACION, FECHA_MODIFICACION, ESTATUS_LINK
            FROM CAT_LUMINARIAS
            WHERE (:P_ONLY_ACTIVE = 0 OR ESTATUS_LINK = 1)
            INTO :ILUMINARIAS_KEY, :CODIGO_LUMINARIA, :DESCRIPCION_LUMINARIA, :MODELO, :POTENCIA, :FLUJO_LUMINOSO, :FECHA_CREACION, :FECHA_MODIFICACION, :ESTATUS_LINK
        DO
            SUSPEND;
    END
    ELSE IF (:P_ILUMINARIAS_KEY > 0) THEN
    BEGIN
        -- Retornar solo un registro específico
        FOR
            SELECT ILUMINARIAS_KEY, CODIGO_LUMINARIA, DESCRIPCION_LUMINARIA, MODELO, POTENCIA, FLUJO_LUMINOSO, FECHA_CREACION, FECHA_MODIFICACION, ESTATUS_LINK
            FROM CAT_LUMINARIAS
            WHERE ILUMINARIAS_KEY = :P_ILUMINARIAS_KEY
            INTO :ILUMINARIAS_KEY, :CODIGO_LUMINARIA, :DESCRIPCION_LUMINARIA, :MODELO, :POTENCIA, :FLUJO_LUMINOSO, :FECHA_CREACION, :FECHA_MODIFICACION, :ESTATUS_LINK
        DO
            SUSPEND;
    END
END^

SET TERM ; ^