SET TERM ^ ;

CREATE OR ALTER PROCEDURE CTLIGHT_SET_CAT_ESTATUS (
    P_ESTATUS_KEY INTEGER,
    P_DESCRIPCION VARCHAR(100)
)
RETURNS (
    ESTATUS_KEY INTEGER,
    RESULTADO INTEGER,
    MSG VARCHAR(100)
)
AS
/*
 * Usuario: Asanchezm
 * Fecha: 20/05/2017
 * Descripción: Inserta o actualiza un registro en la tabla CAT_ESTATUS

 * Modificaciones:
 * 2025/08/21, Asanchezm, 
 */
DECLARE VARIABLE V_ESTATUS_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
    V_CODE = 0;
    V_MSG = '';
    V_ESTATUS_KEY = 0;

    IF (:P_ESTATUS_KEY = 0) THEN
    BEGIN
		INSERT INTO CAT_ESTATUS (DESCRIPCION)
		VALUES (:P_DESCRIPCION)
		RETURNING ESTATUS_KEY INTO :V_ESTATUS_KEY;
    END
    ELSE IF (:P_ESTATUS_KEY > 0) THEN
    BEGIN
		IF (NOT EXISTS(SELECT ESTATUS_KEY
				FROM CAT_ESTATUS
				WHERE (ESTATUS_KEY = :P_ESTATUS_KEY))) THEN
		BEGIN
			V_MSG = 'No existe un registro con este key';
		END
        UPDATE CAT_ESTATUS
        SET DESCRIPCION = :P_DESCRIPCION,
            FECHA_MODIFICACION = CURRENT_TIMESTAMP
        WHERE ESTATUS_KEY = :P_ESTATUS_KEY;
    END

    IF (ROW_COUNT > 0) THEN
    BEGIN
        V_CODE = 1;
        V_MSG = 'Información guardada correctamente';
    END
    ELSE
    BEGIN
        V_CODE = 0;
        V_MSG = 'No se afectó ningún registro';
    END

    ESTATUS_KEY = :V_ESTATUS_KEY;
    RESULTADO = :V_CODE;
    MSG = :V_MSG;
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_GET_CAT_ESTATUS (
	P_ESTATUS_KEY INTEGER = 0
)
RETURNS (
	ESTATUS_KEY INTEGER,
	DESCRIPCION VARCHAR(100),
	FECHA_CREACION TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP
)
AS
BEGIN
	IF (:P_ESTATUS_KEY = 0) THEN
	BEGIN
		-- Retornar listado completo
		FOR
			SELECT ESTATUS_KEY, DESCRIPCION, FECHA_CREACION, FECHA_MODIFICACION
			FROM CAT_ESTATUS
			INTO :ESTATUS_KEY, :DESCRIPCION, :FECHA_CREACION, :FECHA_MODIFICACION
		DO
			SUSPEND;
	END
	ELSE IF (:P_ESTATUS_KEY > 0) THEN
	BEGIN
		-- Retornar solo un registro específico
		FOR
			SELECT ESTATUS_KEY, DESCRIPCION, FECHA_CREACION, FECHA_MODIFICACION
			FROM CAT_ESTATUS
			WHERE ESTATUS_KEY = :P_ESTATUS_KEY
			INTO :ESTATUS_KEY, :DESCRIPCION, :FECHA_CREACION, :FECHA_MODIFICACION
		DO
			SUSPEND;
	END
END^

SET TERM ; ^