SET TERM ^ ;

CREATE OR ALTER PROCEDURE CTLIGHT_SET_CAT_MUNICIPIOS (
    P_MUNICIPIO_KEY INTEGER,
    P_NOMBRE VARCHAR(100),
    P_CLAVE_MUNICIPIO VARCHAR(100),
    P_ESTADO_LINK INTEGER
)
RETURNS (
    MUNICIPIO_KEY INTEGER,
    RESULTADO INTEGER,
    MSG VARCHAR(100)
)
AS
DECLARE VARIABLE V_MUNICIPIO_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
    V_CODE = 0;
    V_MSG = '';
    V_MUNICIPIO_KEY = 0;

    IF (:P_MUNICIPIO_KEY = 0) THEN
    BEGIN
		INSERT INTO CAT_MUNICIPIOS (NOMBRE, CLAVE_MUNICIPIO, ESTADO_LINK)
		VALUES (:P_NOMBRE, :P_CLAVE_MUNICIPIO, :P_ESTADO_LINK)
        RETURNING MUNICIPIO_KEY INTO :V_MUNICIPIO_KEY;
    END
    ELSE IF (:P_MUNICIPIO_KEY > 0) THEN
    BEGIN
		IF (NOT EXISTS(SELECT MUNICIPIO_KEY
				FROM CAT_MUNICIPIOS
				WHERE (MUNICIPIO_KEY = :P_MUNICIPIO_KEY))) THEN
		BEGIN
			V_MSG = 'No existe un registro con este key';
		END
        UPDATE CAT_MUNICIPIOS SET NOMBRE = :P_NOMBRE,
            CLAVE_MUNICIPIO = :P_CLAVE_MUNICIPIO
            WHERE MUNICIPIO_KEY = :P_MUNICIPIO_KEY;
    END
    IF (ROW_COUNT > 0) THEN
    BEGIN
        V_CODE = 1;
        V_MSG = 'Información guardada correctamente';
    END
    ELSE
    BEGIN
        V_CODE = 0;
        V_MSG = 'No se pudo guardar la información';
    END

    RESULTADO = V_CODE;
    MUNICIPIO_KEY = V_MUNICIPIO_KEY;
    MSG = V_MSG;
    SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_GET_CAT_MUNICIPIOS (
    P_MUNICIPIO_KEY INTEGER = 0
)
RETURNS (
    MUNICIPIO_KEY INTEGER,
    ESTADO_LINK INTEGER,
    NOMBRE VARCHAR(100),
    CLAVE_MUNICIPIO VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
)
AS
BEGIN
    IF (:P_MUNICIPIO_KEY = 0) THEN
    BEGIN
        -- Retornar listado completo
        FOR
            SELECT MUNICIPIO_KEY, ESTADO_LINK, NOMBRE, CLAVE_MUNICIPIO, FECHA_CREACION, FECHA_MODIFICACION
            FROM CAT_MUNICIPIOS
            INTO :MUNICIPIO_KEY, :ESTADO_LINK, :NOMBRE, :CLAVE_MUNICIPIO, :FECHA_CREACION, :FECHA_MODIFICACION
        DO
            SUSPEND;
    END
    ELSE IF (:P_MUNICIPIO_KEY > 0) THEN
    BEGIN
        -- Retornar solo un registro específico
        FOR
            SELECT MUNICIPIO_KEY, ESTADO_LINK, NOMBRE, CLAVE_MUNICIPIO, FECHA_CREACION, FECHA_MODIFICACION
            FROM CAT_MUNICIPIOS
            WHERE MUNICIPIO_KEY = :P_MUNICIPIO_KEY
            INTO :MUNICIPIO_KEY, :ESTADO_LINK, :NOMBRE, :CLAVE_MUNICIPIO, :FECHA_CREACION, :FECHA_MODIFICACION
        DO
            SUSPEND;
    END
END^

SET TERM ; ^