SET TERM ^ ;

CREATE OR ALTER PROCEDURE CTLIGHT_SET_CAT_PERMISOS (
	P_PERMISO_KEY INTEGER,
	P_NOMBRE VARCHAR(100),
	P_DESCRIPCION VARCHAR(100),
	P_ESTATUS_LINK INTEGER
)
RETURNS (
	PERMISO_KEY INTEGER,
	RESULTADO INTEGER,
	MSG VARCHAR(100)
)
AS
DECLARE VARIABLE V_PERMISO_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
	V_CODE = 0;
	V_MSG = '';
	V_PERMISO_KEY = 0;

	IF (:P_PERMISO_KEY = 0) THEN
	BEGIN
		INSERT INTO CAT_PERMISOS (NOMBRE, DESCRIPCION, ESTATUS_LINK)
		VALUES (:P_NOMBRE, :P_DESCRIPCION, :P_ESTATUS_LINK)
		RETURNING PERMISO_KEY INTO :V_PERMISO_KEY;
	END
	ELSE IF (:P_PERMISO_KEY > 0) THEN
	BEGIN
		IF (NOT EXISTS(SELECT PERMISO_KEY
				FROM CAT_PERMISOS
				WHERE (PERMISO_KEY = :P_PERMISO_KEY))) THEN
		BEGIN
			V_MSG = 'No existe un registro con este key';
		END
		UPDATE CAT_PERMISOS
		SET NOMBRE = :P_NOMBRE,
			DESCRIPCION = :P_DESCRIPCION,
			ESTATUS_LINK = :P_ESTATUS_LINK,
			FECHA_MODIFICACION = CURRENT_TIMESTAMP
		WHERE PERMISO_KEY = :P_PERMISO_KEY;
	END
	IF (ROW_COUNT > 0) THEN
	BEGIN
		V_CODE = 1;
		V_MSG = 'Información guardada correctamente';
	END
	ELSE
	BEGIN
		V_CODE = 0;
		V_MSG = 'No se pudo guardar la información';
	END

	RESULTADO = V_CODE;
	PERMISO_KEY = V_PERMISO_KEY;
	MSG = V_MSG;
	SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_DEL_CAT_PERMISOS (
	P_PERMISO_KEY INTEGER
)
RETURNS (
	PERMISO_KEY INTEGER,
	RESULTADO INTEGER,
	MSG VARCHAR(100)
)
AS
DECLARE VARIABLE V_PERMISO_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
	V_CODE = 0;
	V_MSG = '';
	V_PERMISO_KEY = 0;

	IF (NOT EXISTS(SELECT PERMISO_KEY
			FROM CAT_PERMISOS
			WHERE (PERMISO_KEY = :P_PERMISO_KEY))) THEN
	BEGIN
		V_MSG = 'No existe un registro con este key';
	END

	UPDATE CAT_PERMISOS
	SET ESTATUS_LINK = 2,
		FECHA_MODIFICACION = CURRENT_TIMESTAMP
	WHERE PERMISO_KEY = :P_PERMISO_KEY;
	IF (ROW_COUNT > 0) THEN
	BEGIN
		V_CODE = 1;
		V_MSG = 'Registro eliminado correctamente';
	END
	ELSE
	BEGIN
		V_CODE = 0;
		V_MSG = 'No se pudo eliminar el registro';
	END
	RESULTADO = V_CODE;
	PERMISO_KEY = V_PERMISO_KEY;
	MSG = V_MSG;
	SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_GET_CAT_PERMISOS (
	P_PERMISO_KEY INTEGER = 0,
	P_ONLY_ACTIVE SMALLINT = 0
)
RETURNS (
	PERMISO_KEY INTEGER,
	NOMBRE VARCHAR(100),
	DESCRIPCION VARCHAR(100),
	FECHA_CREACION TIMESTAMP,
	FECHA_MODIFICACION TIMESTAMP,
	ESTATUS_LINK INTEGER
)
AS
BEGIN
	IF (:P_PERMISO_KEY = 0) THEN
	BEGIN
		-- Retornar listado completo
		FOR
			SELECT PERMISO_KEY, NOMBRE, DESCRIPCION, FECHA_CREACION, FECHA_MODIFICACION, ESTATUS_LINK
			FROM CAT_PERMISOS
			WHERE (:P_ONLY_ACTIVE = 0 OR ESTATUS_LINK = 1)
			INTO :PERMISO_KEY, :NOMBRE, :DESCRIPCION, :FECHA_CREACION, :FECHA_MODIFICACION, :ESTATUS_LINK
		DO
			SUSPEND;
	END
	ELSE IF (:P_PERMISO_KEY > 0) THEN
	BEGIN
		-- Retornar solo un registro específico
		FOR
			SELECT PERMISO_KEY, NOMBRE, DESCRIPCION, FECHA_CREACION, FECHA_MODIFICACION, ESTATUS_LINK
			FROM CAT_PERMISOS
			WHERE PERMISO_KEY = :P_PERMISO_KEY
			INTO :PERMISO_KEY, :NOMBRE, :DESCRIPCION, :FECHA_CREACION, :FECHA_MODIFICACION, :ESTATUS_LINK
		DO
			SUSPEND;
	END
END^

SET TERM ; ^