SET TERM ^ ;

CREATE OR ALTER PROCEDURE CTLIGHT_SET_CUADRILLA_PROYECTO (
	P_CUADRILLA_PROYECTO_KEY INTEGER,
	P_PROYECTO_KEY INTEGER,
	P_CUADRILLA_KEY INTEGER,
	P_ESTATUS_LINK INTEGER
)
RETURNS (
	CUADRILLA_PROYECTO_KEY INTEGER,
	RESULTADO INTEGER,
	MSG VARCHAR(100)
)
AS
DECLARE VARIABLE V_CUADRILLA_PROYECTO_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
	V_CODE = 0;
	V_MSG = '';
	V_CUADRILLA_PROYECTO_KEY = 0;

	IF (:P_CUADRILLA_PROYECTO_KEY = 0) THEN
	BEGIN
		INSERT INTO CUADRILLA_PROYECTO (CUADRILLA_LINK, PROYECTO_LINK, ESTATUS_LINK)
		VALUES (:P_CUADRILLA_KEY, :P_PROYECTO_KEY, :P_ESTATUS_LINK)
		RETURNING CUADRILLA_PROYECTO_KEY INTO :V_CUADRILLA_PROYECTO_KEY;
	END
	ELSE IF (:P_CUADRILLA_PROYECTO_KEY > 0) THEN
	BEGIN
		IF (NOT EXISTS(SELECT CUADRILLA_PROYECTO_KEY
				FROM CUADRILLA_PROYECTO
				WHERE (CUADRILLA_PROYECTO_KEY = :P_CUADRILLA_PROYECTO_KEY))) THEN
		BEGIN
			V_MSG = 'No existe un registro con este key';
		END
		UPDATE CUADRILLA_PROYECTO
		SET CUADRILLA_LINK = :P_CUADRILLA_KEY,
			PROYECTO_LINK = :P_PROYECTO_KEY,
			ESTATUS_LINK = :P_ESTATUS_LINK
		WHERE CUADRILLA_PROYECTO_KEY = :P_CUADRILLA_PROYECTO_KEY;
	END
	IF (ROW_COUNT > 0) THEN
	BEGIN
		V_CODE = 1;
		V_MSG = 'Información guardada correctamente';
	END
	ELSE
	BEGIN
		V_CODE = 0;
		V_MSG = 'No se pudo guardar la información';
	END

	RESULTADO = V_CODE;
	CUADRILLA_PROYECTO_KEY = V_CUADRILLA_PROYECTO_KEY;
	MSG = V_MSG;
	SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_DEL_CUADRILLA_PROYECTO (
	P_CUADRILLA_PROYECTO_KEY INTEGER
)
RETURNS (
	CUADRILLA_PROYECTO_KEY INTEGER,
	RESULTADO INTEGER,
	MSG VARCHAR(100)
)
AS
DECLARE VARIABLE V_CUADRILLA_PROYECTO_KEY INTEGER;
DECLARE VARIABLE V_CODE INTEGER;
DECLARE VARIABLE V_MSG VARCHAR(100);
BEGIN
	V_CODE = 0;
	V_MSG = '';
	V_CUADRILLA_PROYECTO_KEY = 0;

	IF (NOT EXISTS(SELECT CUADRILLA_PROYECTO_KEY
			FROM CUADRILLA_PROYECTO
			WHERE (CUADRILLA_PROYECTO_KEY = :P_CUADRILLA_PROYECTO_KEY))) THEN    
	BEGIN
		V_MSG = 'No existe un registro con este key';
	END

	UPDATE CUADRILLA_PROYECTO
	SET ESTATUS_LINK = 2
	WHERE CUADRILLA_PROYECTO_KEY = :P_CUADRILLA_PROYECTO_KEY;
	IF (ROW_COUNT > 0) THEN
	BEGIN
		V_CODE = 1;
		V_MSG = 'Registro eliminado correctamente';
	END
	ELSE
	BEGIN
		V_CODE = 0;
		V_MSG = 'No se pudo eliminar el registro';
	END
	RESULTADO = V_CODE;
	CUADRILLA_PROYECTO_KEY = V_CUADRILLA_PROYECTO_KEY;
	MSG = V_MSG;
	SUSPEND;
END^

CREATE OR ALTER PROCEDURE CTLIGHT_GET_CUADRILLA_PROYECTO (
	P_CUADRILLA_PROYECTO_KEY INTEGER = 0,
	P_ONLY_ACTIVE SMALLINT = 0
)
RETURNS (
	CUADRILLA_PROYECTO_KEY INTEGER,
	CUADRILLA_LINK INTEGER,
	PROYECTO_LINK INTEGER,
	FECHA_CREACION TIMESTAMP,
	ESTATUS_LINK INTEGER
)
AS
BEGIN
	IF (:P_CUADRILLA_PROYECTO_KEY = 0) THEN
	BEGIN
		-- Retornar listado completo
		FOR
			SELECT CUADRILLA_PROYECTO_KEY, CUADRILLA_LINK, PROYECTO_LINK, FECHA_CREACION, ESTATUS_LINK
			FROM CUADRILLA_PROYECTO
			WHERE (:P_ONLY_ACTIVE = 0 OR ESTATUS_LINK = 1)
			INTO :CUADRILLA_PROYECTO_KEY, :CUADRILLA_LINK, :PROYECTO_LINK, :FECHA_CREACION, :ESTATUS_LINK
		DO
			SUSPEND;
	END
	ELSE IF (:P_CUADRILLA_PROYECTO_KEY > 0) THEN
	BEGIN
		-- Retornar solo un registro específico
		FOR
			SELECT CUADRILLA_PROYECTO_KEY, CUADRILLA_LINK, PROYECTO_LINK, FECHA_CREACION, ESTATUS_LINK
			FROM CUADRILLA_PROYECTO
			WHERE CUADRILLA_PROYECTO_KEY = :P_CUADRILLA_PROYECTO_KEY
			INTO :CUADRILLA_PROYECTO_KEY, :CUADRILLA_LINK, :PROYECTO_LINK, :FECHA_CREACION, :ESTATUS_LINK
		DO
			SUSPEND;
	END
END^    

SET TERM ; ^